### ISSUE TITLE
`addOutputs` stripping underscores from names

### ISSUE THREAD

**Issue by justindra** [sst/sst#1863]
Not sure if this is intended or not. But just noticed that the stack output names do not match between what we provide and what is output.

```ts
  stack.addOutputs({
    API_URL: api.url,
    AUTH_CLIENT_ID: auth.cdk.userPoolClient.userPoolClientId,
    AUTH_DOMAIN: domain.domainName,
  });
```

outputs:
```
Stack justin-mws-Api
  Status: deployed
  Outputs:
    APIURL: ...
    AUTHCLIENTID: ...
    AUTHDOMAIN: ....
```

So it's stripping the `_` (underscores) out of the names.
