### ISSUE TITLE
Cannot find module @aws-sdk/types with yarn pnpm linker

### ISSUE THREAD

**Issue by jonmast** [sst/sst#3140]
Both the `sst` and `sst-aws-cdk` package have missing dependencies that cause errors with yarn's pnpm linker. Unlike pnpm yarn doesn't allow dependencies to access other dependencies they haven't explicitly declared. This is roughly equivalent to setting `hoist=false` on pnpm.

For example, `sst` [imports @aws-sdk/types in credentials.ts](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/credentials.ts#L1), but doesn't declare it as a dependency. When run with yarn it results in the error `Error: Cannot find module '@aws-sdk/types'`.

I can work around this by manually specifying the dependencies in `.yarnrc.yaml`, but ideally the `package.json` would be updated to appropriately declare the dependencies.

```yaml
packageExtensions:
  "sst@*":
    peerDependencies:
      "@aws-sdk/types": "*"
  "sst-aws-cdk@*":
    peerDependencies:
      "@aws-cdk/cx-api": "*"
      "@aws-cdk/cloud-assembly-schema": "*"
      "@aws-cdk/cloudformation-diff": "*"
      "aws-sdk": "*"
    dependencies:
      "fs-extra": "*"
```
