### ISSUE TITLE
Git Large File Storage (LFS) support in Next.js public folder

### ISSUE THREAD

**Issue by enzoferey** [sst/sst#3801]
Hi ! 

We are building our Next.js website via Github Actions and we have added some large files inside the Next.js public folder using LFS but they don't work as other assets that are not being tracked via LFS. Does SST support files on LFS? Is there additional configuration for this use case?

Example: https://app.domenation.io/static/images/nfts/comic-page/1/0.gif

As you may see, the content of the image is just a pointer. Running a cURL ouputs =>

```
version https://git-lfs.github.com/spec/v1
oid sha256:62ebf4559f685727d3d0ab42375c6e2e4b6030281e3f5984783cc3ed81d41aa5
size 199985100
```

Our Github Action looks like:

```
name: Deploy to develop
on:
  push:
    branches:
      - develop

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy-dapp:
    name: Deploy dApp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.13.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::581378346902:role/github_actions_deployer
          aws-region: eu-west-1

      - name: Run deploy script
        run: |
          sst deploy --stage dev
        env:
```

We have tried turning on the `lfs` flag on the checkout action + adding more git lfs commands like `pull`, `fetch`, `checkout` and others without success.

When we `cat` the file, we can see the content of it being there, but the app build does not pick up the content, just the pointer.

Thank you 🙏 

---

On Discord =>

https://discord.com/channels/983865673656705025/1256206472610582548/1256206472610582548
