### ISSUE TITLE
Setting Node.js compatibility flags for Cloudlfare Workers via SST

### ISSUE THREAD

**Issue by keturiosakys** [sst/sst#4135]
Hey there! I'm helping out someone trying out our client library that works on Cloudflare Workers using some of the Node.js APIs (namely for OpenTelemetry). https://github.com/fiberplane/fpx/issues/248

The gist of the issue is:

When working with Cloudflare Workers vanilla-directly I can configure compatibility flags for Node.js by setting the following in `wrangler.toml`:

```toml
name = "cloudflare-hono-sst"
compatibility_date = "2024-09-11"
compatibility_flags = [ "nodejs_compat" ] # ← here
```

However, setting the same  in a project using SST doesn't work (as I understand SST fully leans into the `sst.config.ts` and doesn't utilize the `wrangler.toml` at all). I tried several of the suggested solutions listed here: https://github.com/sst/ion/issues/357 but none have yielded the result.

The repro repo is here: https://github.com/keturiosakys/cloudflare-hono-sst
