### ISSUE TITLE
bug?: github action cache still redownloads provider

### ISSUE THREAD

**Issue by iOSonntag** [sst/sst#4204]
When we remove everything in the `.sst` folder except the `platform` folder another sst deploy/dev command wont reinstall the providers.

When we cache the platform folder in github actions using this command:

```yaml
- name: Cache SST Platform
      uses: actions/cache@v3
      with:
        path: sst/.sst/platform
        key: ${{ runner.os }}-sst-platform-${{ hashFiles('sst/pnpm-lock.yaml', 'sst/sst.config.ts') }}
```

(note: the whole sst project is in the subdir sst)

Then the proiders get reinstalled every single github action run, is this intended behaviour? Is there any way to bypass this?
