### ISSUE TITLE
feature: support pulumi config

### ISSUE THREAD

**Issue by JanStevens** [sst/sst#4881]
Hi,

When using Pulumi directly you have the ability to specify configuration (ref: https://www.pulumi.com/docs/concepts/config) in your `Pulumi.yaml` file like the following:

```yaml
config:
  # Custom configuration goes here
  backend:apiPublicDomainName:
    type: string
    description: "The public domain name for the API"

  backend:frontendPublicDomainName:
    type: string
    description: "The public domain name for the frontend"
```

This allows to enforce that every Pulumi stack file contains the above configuration like so

```yaml
config:
  backend:apiPublicDomainName: "api.backend.dev"
  backend:frontendPublicDomainName: "backend.dev"⏎
```

And finally enforcing the requirement to be there in the Pulumi code

```typescript
const config = new pulumi.Config();
pulumi.log.info(config.require('apiPublicDomainName'));
```

Thus ensuring that `apiPublicDomainName` is always set

---

Translating this to ION it would mean you can add configuration per stage. On "development" stage my domain name would be "api.dev.backend.dev" vs on "production" it would be "api.backend.dev". A lot of times we need this kinda of configuration and right now I have no way to define this in ion (or SST).

The only option is to riddle your infra code with conditionals depending on stages but if an additional stage is provisioned (or even your local user stage during development) you suddenly have  to update everything and often forget / miss different pieces of configuration.

Finally since `$app.stage` is only evaluated in the `run` function having this as a global constant somewhere doesn't work:

```typescript
export const API_PUBLIC_DOMAIN = $app.stage === 'production' ? 'api.backend.dev' : 'api.dev.backend.dev'
```

Typically we use this to configure: domains, certificates, external integrations configuration (everything which is not a secret for example, like external api urls, client ids and so on)

Terraform has the same concept called tfvars files (ref: https://developer.hashicorp.com/terraform/language/values/variables#assigning-values-to-root-module-variables)
